master_image: str(required=True)
master_flavor: str(required=True)
mysql: str(required=True)
openstack_url: str(required=True)
nova: include('nova_spec')
region_name: str(required=True)
scale_node_count: int(min=1, required=True)
remove_node_count: int(min=1, required=True)

---
nova_spec:
  auth_url: str(required=True)
  auth_type: str(required=True)
  project_domain: str(required=True)
  user_domain: str(required=True)
  project_name: str(required=True)
  user_name: str(required=True)
  password: str(required=True)
  region_name: str(required=True)
