[unix_http_server]
file=/var/run/supervisor.sock

[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:fastapi]
command=/usr/local/bin/gunicorn -c /etc/dingo-command/gunicorn.py main:app
directory=/opt/auto_test
autostart=true
autorestart=true
stdout_logfile=/var/log/dingo-command.log
stderr_logfile=/var/log/dingo-command.err

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock
prompt=dingo-command-supervisor